sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: VDY3AbzsawgoyBQ77X+tG5GFiV0yf1rvDxfCjKRhmzLNiGde3z0P6WCL5aOfRVJ58mIU0DjDYXTUzrM0O1YYuXSO8rNl2o3Fknq8bZDiT1jDvb8vowAetRA0tLGDF3YO3je4g7dgGa1wIuN+ryiZT3/nY/EOa4rwaPJj9ji25sOeDgoxnAehOEDrUFvcLLHjgFE3rkQacP8IuxNpaiXYG0eqfGG5894RuB/Gl379M5PWMMHEekkqTX0bItmcjokOLnltvVL1eS6GJgfNd6+xgCm5e3ucB6fhoZVNiu19G+SPBUTlNxkymltU6Zr16ZHDmpxGEkytJhyNi0f2FD7xgSn0sIjydesQvMm7eHQR3Qf6VIRDtj7WtQLQ2iO+HU21R/+MjayiyQsSWduJRe9/p8YU1RKJvVRHL5OiAeBDxG9sJVG6L+hFEkF0EMwJEZgb9NC/ksFUxPV6aqVNNfoR68ukE7ex1fzdtj1xkWzmgbqdCGQ1VOzK4EtOxJNfQoGczYwYxVDN0CupijkrDEBX9QeRs/v3W/3dYSV1m1oWnv7ujb+ui80/YB/jwhbT8u2FZW3Z5Aocbo+NQjaTha2QskTWdDEKS/j0mZr0uNurz2kFZOHfrAeWW+KIMdcSsipxX0odU/qmed2Eb6DoHiG4yam6jAtzUXYFdFSgAysmqGU=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Andersen-s-Fairy-Tales_1597
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy